package com.zjjzfy.pojo;

import javax.persistence.Id;
import java.io.Serializable;

public class JfDeliverOrderExtra implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order_extra.billno
     *
     * @mbggenerated
     */
    @Id
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order_extra.cust_name
     *
     * @mbggenerated
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order_extra.cust_tel
     *
     * @mbggenerated
     */
    private String custTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order_extra.cust_addr
     *
     * @mbggenerated
     */
    private String custAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order_extra.process_status
     *
     * @mbggenerated
     */
    private String processStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jf_deliver_order_extra
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order_extra.billno
     *
     * @return the value of jf_deliver_order_extra.billno
     *
     * @mbggenerated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order_extra.billno
     *
     * @param billno the value for jf_deliver_order_extra.billno
     *
     * @mbggenerated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order_extra.cust_name
     *
     * @return the value of jf_deliver_order_extra.cust_name
     *
     * @mbggenerated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order_extra.cust_name
     *
     * @param custName the value for jf_deliver_order_extra.cust_name
     *
     * @mbggenerated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order_extra.cust_tel
     *
     * @return the value of jf_deliver_order_extra.cust_tel
     *
     * @mbggenerated
     */
    public String getCustTel() {
        return custTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order_extra.cust_tel
     *
     * @param custTel the value for jf_deliver_order_extra.cust_tel
     *
     * @mbggenerated
     */
    public void setCustTel(String custTel) {
        this.custTel = custTel == null ? null : custTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order_extra.cust_addr
     *
     * @return the value of jf_deliver_order_extra.cust_addr
     *
     * @mbggenerated
     */
    public String getCustAddr() {
        return custAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order_extra.cust_addr
     *
     * @param custAddr the value for jf_deliver_order_extra.cust_addr
     *
     * @mbggenerated
     */
    public void setCustAddr(String custAddr) {
        this.custAddr = custAddr == null ? null : custAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order_extra.process_status
     *
     * @return the value of jf_deliver_order_extra.process_status
     *
     * @mbggenerated
     */
    public String getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order_extra.process_status
     *
     * @param processStatus the value for jf_deliver_order_extra.process_status
     *
     * @mbggenerated
     */
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus == null ? null : processStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jf_deliver_order_extra
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", billno=").append(billno);
        sb.append(", custName=").append(custName);
        sb.append(", custTel=").append(custTel);
        sb.append(", custAddr=").append(custAddr);
        sb.append(", processStatus=").append(processStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}