package com.zjjzfy.pojo;

import javax.persistence.Id;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class JfDeliverOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.id
     *
     * @mbggenerated
     */
    @Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.branchid
     *
     * @mbggenerated
     */
    private Integer branchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.billno
     *
     * @mbggenerated
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.employeeid
     *
     * @mbggenerated
     */
    private Integer employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.total_quantity
     *
     * @mbggenerated
     */
    private Integer totalQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.clientno
     *
     * @mbggenerated
     */
    private String clientno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_deliver_order.out_time
     *
     * @mbggenerated
     */
    private Date outTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jf_deliver_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.id
     *
     * @return the value of jf_deliver_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.id
     *
     * @param id the value for jf_deliver_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.branchid
     *
     * @return the value of jf_deliver_order.branchid
     *
     * @mbggenerated
     */
    public Integer getBranchid() {
        return branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.branchid
     *
     * @param branchid the value for jf_deliver_order.branchid
     *
     * @mbggenerated
     */
    public void setBranchid(Integer branchid) {
        this.branchid = branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.billno
     *
     * @return the value of jf_deliver_order.billno
     *
     * @mbggenerated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.billno
     *
     * @param billno the value for jf_deliver_order.billno
     *
     * @mbggenerated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.employeeid
     *
     * @return the value of jf_deliver_order.employeeid
     *
     * @mbggenerated
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.employeeid
     *
     * @param employeeid the value for jf_deliver_order.employeeid
     *
     * @mbggenerated
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.total_price
     *
     * @return the value of jf_deliver_order.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.total_price
     *
     * @param totalPrice the value for jf_deliver_order.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.status
     *
     * @return the value of jf_deliver_order.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.status
     *
     * @param status the value for jf_deliver_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.create_date
     *
     * @return the value of jf_deliver_order.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.create_date
     *
     * @param createDate the value for jf_deliver_order.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.type
     *
     * @return the value of jf_deliver_order.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.type
     *
     * @param type the value for jf_deliver_order.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.remark
     *
     * @return the value of jf_deliver_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.remark
     *
     * @param remark the value for jf_deliver_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.total_quantity
     *
     * @return the value of jf_deliver_order.total_quantity
     *
     * @mbggenerated
     */
    public Integer getTotalQuantity() {
        return totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.total_quantity
     *
     * @param totalQuantity the value for jf_deliver_order.total_quantity
     *
     * @mbggenerated
     */
    public void setTotalQuantity(Integer totalQuantity) {
        this.totalQuantity = totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.clientno
     *
     * @return the value of jf_deliver_order.clientno
     *
     * @mbggenerated
     */
    public String getClientno() {
        return clientno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.clientno
     *
     * @param clientno the value for jf_deliver_order.clientno
     *
     * @mbggenerated
     */
    public void setClientno(String clientno) {
        this.clientno = clientno == null ? null : clientno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_deliver_order.out_time
     *
     * @return the value of jf_deliver_order.out_time
     *
     * @mbggenerated
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_deliver_order.out_time
     *
     * @param outTime the value for jf_deliver_order.out_time
     *
     * @mbggenerated
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jf_deliver_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", branchid=").append(branchid);
        sb.append(", billno=").append(billno);
        sb.append(", employeeid=").append(employeeid);
        sb.append(", totalPrice=").append(totalPrice);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append(", type=").append(type);
        sb.append(", remark=").append(remark);
        sb.append(", totalQuantity=").append(totalQuantity);
        sb.append(", clientno=").append(clientno);
        sb.append(", outTime=").append(outTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}