package com.zjjzfy.pojo;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Table(name = "tb_ip_org")
public class TbIpOrg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ip_org.ip
     *
     * @mbggenerated
     */
    @Id
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ip_org.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ip_org.branchno
     *
     * @mbggenerated
     */
    private String branchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ip_org.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ip_org.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ip_org
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ip_org.ip
     *
     * @return the value of tb_ip_org.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ip_org.ip
     *
     * @param ip the value for tb_ip_org.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ip_org.org_id
     *
     * @return the value of tb_ip_org.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ip_org.org_id
     *
     * @param orgId the value for tb_ip_org.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ip_org.branchno
     *
     * @return the value of tb_ip_org.branchno
     *
     * @mbggenerated
     */
    public String getBranchno() {
        return branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ip_org.branchno
     *
     * @param branchno the value for tb_ip_org.branchno
     *
     * @mbggenerated
     */
    public void setBranchno(String branchno) {
        this.branchno = branchno == null ? null : branchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ip_org.org_name
     *
     * @return the value of tb_ip_org.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ip_org.org_name
     *
     * @param orgName the value for tb_ip_org.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ip_org.remark
     *
     * @return the value of tb_ip_org.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ip_org.remark
     *
     * @param remark the value for tb_ip_org.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ip_org
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ip=").append(ip);
        sb.append(", orgId=").append(orgId);
        sb.append(", branchno=").append(branchno);
        sb.append(", orgName=").append(orgName);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}