package com.zjjzfy.pojo;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Table(name = "tb_purchase_detail")
public class TbPurchaseDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_purchase_detail.id
     *
     * @mbggenerated
     */
    @Id
    private Integer id;

    private Integer purchaseFormId;

    private String purchaseBillno;

    private Integer productId;

    private Integer purchaseQuantity;

    private Integer storageQuantity;

    private Integer onQuality;

    private Integer surplusQuantity;

    private Byte status;

    private BigDecimal purchasePrice;

    private BigDecimal settlePrice;

    private Date createDate;

    private Date updateDate;

    private String productColor;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPurchaseFormId() {
        return purchaseFormId;
    }

    public void setPurchaseFormId(Integer purchaseFormId) {
        this.purchaseFormId = purchaseFormId;
    }

    public String getPurchaseBillno() {
        return purchaseBillno;
    }

    public void setPurchaseBillno(String purchaseBillno) {
        this.purchaseBillno = purchaseBillno == null ? null : purchaseBillno.trim();
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getPurchaseQuantity() {
        return purchaseQuantity;
    }

    public void setPurchaseQuantity(Integer purchaseQuantity) {
        this.purchaseQuantity = purchaseQuantity;
    }

    public Integer getStorageQuantity() {
        return storageQuantity;
    }

    public void setStorageQuantity(Integer storageQuantity) {
        this.storageQuantity = storageQuantity;
    }

    public Integer getOnQuality() {
        return onQuality;
    }

    public void setOnQuality(Integer onQuality) {
        this.onQuality = onQuality;
    }

    public Integer getSurplusQuantity() {
        return surplusQuantity;
    }

    public void setSurplusQuantity(Integer surplusQuantity) {
        this.surplusQuantity = surplusQuantity;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public BigDecimal getPurchasePrice() {
        return purchasePrice;
    }

    public void setPurchasePrice(BigDecimal purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    public BigDecimal getSettlePrice() {
        return settlePrice;
    }

    public void setSettlePrice(BigDecimal settlePrice) {
        this.settlePrice = settlePrice;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getProductColor() {
        return productColor;
    }

    public void setProductColor(String productColor) {
        this.productColor = productColor == null ? null : productColor.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", purchaseFormId=").append(purchaseFormId);
        sb.append(", purchaseBillno=").append(purchaseBillno);
        sb.append(", productId=").append(productId);
        sb.append(", purchaseQuantity=").append(purchaseQuantity);
        sb.append(", storageQuantity=").append(storageQuantity);
        sb.append(", onQuality=").append(onQuality);
        sb.append(", surplusQuantity=").append(surplusQuantity);
        sb.append(", status=").append(status);
        sb.append(", purchasePrice=").append(purchasePrice);
        sb.append(", settlePrice=").append(settlePrice);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", productColor=").append(productColor);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}