package com.zjjzfy.pojo;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

@Table(name = "tb_repository_record")
public class TbRepositoryRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_repository_record.id
     *
     * @mbggenerated
     */
    @Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_repository_record.billno
     *
     * @mbggenerated
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_repository_record.supply_org_id
     *
     * @mbggenerated
     */
    private Integer supplyOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_repository_record.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_repository_record.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_repository_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_repository_record.id
     *
     * @return the value of tb_repository_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_repository_record.id
     *
     * @param id the value for tb_repository_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_repository_record.billno
     *
     * @return the value of tb_repository_record.billno
     *
     * @mbggenerated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_repository_record.billno
     *
     * @param billno the value for tb_repository_record.billno
     *
     * @mbggenerated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_repository_record.supply_org_id
     *
     * @return the value of tb_repository_record.supply_org_id
     *
     * @mbggenerated
     */
    public Integer getSupplyOrgId() {
        return supplyOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_repository_record.supply_org_id
     *
     * @param supplyOrgId the value for tb_repository_record.supply_org_id
     *
     * @mbggenerated
     */
    public void setSupplyOrgId(Integer supplyOrgId) {
        this.supplyOrgId = supplyOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_repository_record.create_date
     *
     * @return the value of tb_repository_record.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_repository_record.create_date
     *
     * @param createDate the value for tb_repository_record.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_repository_record.status
     *
     * @return the value of tb_repository_record.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_repository_record.status
     *
     * @param status the value for tb_repository_record.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repository_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", billno=").append(billno);
        sb.append(", supplyOrgId=").append(supplyOrgId);
        sb.append(", createDate=").append(createDate);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}