package com.zjjzfy.pojo;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

@Table(name = "tb_user_info")
public class TbUserInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.uid
     *
     * @mbggenerated
     */
    @Id
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.orgid
     *
     * @mbggenerated
     */
    private Integer orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.operator
     *
     * @mbggenerated
     */
    private Integer operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.last_pwd_modifytime
     *
     * @mbggenerated
     */
    private Date lastPwdModifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.column1
     *
     * @mbggenerated
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.column2
     *
     * @mbggenerated
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.column3
     *
     * @mbggenerated
     */
    private Integer column3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.column4
     *
     * @mbggenerated
     */
    private Integer column4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.uid
     *
     * @return the value of tb_user_info.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.uid
     *
     * @param uid the value for tb_user_info.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.username
     *
     * @return the value of tb_user_info.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.username
     *
     * @param username the value for tb_user_info.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.name
     *
     * @return the value of tb_user_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.name
     *
     * @param name the value for tb_user_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.password
     *
     * @return the value of tb_user_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.password
     *
     * @param password the value for tb_user_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.salt
     *
     * @return the value of tb_user_info.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.salt
     *
     * @param salt the value for tb_user_info.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.state
     *
     * @return the value of tb_user_info.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.state
     *
     * @param state the value for tb_user_info.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.orgid
     *
     * @return the value of tb_user_info.orgid
     *
     * @mbggenerated
     */
    public Integer getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.orgid
     *
     * @param orgid the value for tb_user_info.orgid
     *
     * @mbggenerated
     */
    public void setOrgid(Integer orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.addtime
     *
     * @return the value of tb_user_info.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.addtime
     *
     * @param addtime the value for tb_user_info.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.operator
     *
     * @return the value of tb_user_info.operator
     *
     * @mbggenerated
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.operator
     *
     * @param operator the value for tb_user_info.operator
     *
     * @mbggenerated
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.last_pwd_modifytime
     *
     * @return the value of tb_user_info.last_pwd_modifytime
     *
     * @mbggenerated
     */
    public Date getLastPwdModifytime() {
        return lastPwdModifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.last_pwd_modifytime
     *
     * @param lastPwdModifytime the value for tb_user_info.last_pwd_modifytime
     *
     * @mbggenerated
     */
    public void setLastPwdModifytime(Date lastPwdModifytime) {
        this.lastPwdModifytime = lastPwdModifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.last_login_time
     *
     * @return the value of tb_user_info.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.last_login_time
     *
     * @param lastLoginTime the value for tb_user_info.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.remark
     *
     * @return the value of tb_user_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.remark
     *
     * @param remark the value for tb_user_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.column1
     *
     * @return the value of tb_user_info.column1
     *
     * @mbggenerated
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.column1
     *
     * @param column1 the value for tb_user_info.column1
     *
     * @mbggenerated
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.column2
     *
     * @return the value of tb_user_info.column2
     *
     * @mbggenerated
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.column2
     *
     * @param column2 the value for tb_user_info.column2
     *
     * @mbggenerated
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.column3
     *
     * @return the value of tb_user_info.column3
     *
     * @mbggenerated
     */
    public Integer getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.column3
     *
     * @param column3 the value for tb_user_info.column3
     *
     * @mbggenerated
     */
    public void setColumn3(Integer column3) {
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.column4
     *
     * @return the value of tb_user_info.column4
     *
     * @mbggenerated
     */
    public Integer getColumn4() {
        return column4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.column4
     *
     * @param column4 the value for tb_user_info.column4
     *
     * @mbggenerated
     */
    public void setColumn4(Integer column4) {
        this.column4 = column4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", username=").append(username);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append(", state=").append(state);
        sb.append(", orgid=").append(orgid);
        sb.append(", addtime=").append(addtime);
        sb.append(", operator=").append(operator);
        sb.append(", lastPwdModifytime=").append(lastPwdModifytime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", remark=").append(remark);
        sb.append(", column1=").append(column1);
        sb.append(", column2=").append(column2);
        sb.append(", column3=").append(column3);
        sb.append(", column4=").append(column4);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public String getMixSalt(){
        return username+salt;
    }
}