package com.zjjzfy.interfaces;

import com.zjjzfy.pojo.TbInvoice;
import com.zjjzfy.pojo.TbInvoiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbInvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    int countByExample(TbInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    int deleteByExample(TbInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    int insert(TbInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    int insertSelective(TbInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    List<TbInvoice> selectByExample(TbInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    TbInvoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbInvoice record, @Param("example") TbInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbInvoice record, @Param("example") TbInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbInvoice record);
}