shiro:
  hashAlgorithmName: md5
  hashIterations: 2
  globalSessionTimeout: 900000
  loginUrl: /mbl/login
  successUrl: /mbl/home
  unauthorizedUrl: /403
  filterChain: /purchase/pad/**, /upload/**, /css/**, /image/**, /js/**, /layui/**, /mbl/loginSelect, /mbl/login, /mbl/logon, /favicon.ico, /**
  filterChainAuth: anon, anon, anon, anon, anon, anon, anon, anon, anon, anon, authc
#  filterChain: { "/static/**": anon, "/login": anon, "/logout": logout, "/**": authc }
#    "[/static/**]": anon
#    "[/login]": anon
#    "[/logout]": logout
#    "[/**]": authc